=== nirdslab/streaminghub/dfs/analytic.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "description": "schema of an analytic",
  "type": "object",
  "required": [
    "$schema",
    "info",
    "sources",
    "fields",
    "inputs",
    "streams"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "info": {
      "$ref": "https://raw.githubusercontent.com/nirdslab/streaminghub/master/dfs/dfs.schema.json#/definitions/info"
    },
    "sources": {
      "description": "data sources for generating the analytic",
      "$ref": "https://raw.githubusercontent.com/nirdslab/streaminghub/master/dfs/dfs.schema.json#/definitions/refs"
    },
    "fields": {
      "$ref": "https://raw.githubusercontent.com/nirdslab/streaminghub/master/dfs/dfs.schema.json#/definitions/fields"
    },
    "inputs": {
      "description": "information on the inputs consumed",
      "$ref": "https://raw.githubusercontent.com/nirdslab/streaminghub/master/dfs/dfs.schema.json#/definitions/refs"
    },
    "streams": {
      "description": "information on the output streams generated",
      "$ref": "https://raw.githubusercontent.com/nirdslab/streaminghub/master/dfs/dfs.schema.json#/definitions/streams"
    }
  }
}

=== nirdslab/streaminghub/dfs/samples/master/analytic.sample.json
{
  "$schema": "../../analytic.schema.json",
  "info": {
    "version": "1.0.0",
    "timestamp": "2020-01-01T00:00:00Z",
    "checksum": "010203040506070809000A0B0C0D0E0F"
  },
  "sources": {
    "e4": "datasource.sample.json"
  },
  "fields": {
    "t": "#/sources/e4/fields/t",
    "hr": {
      "name": "heart rate",
      "description": "heart rate in bpm",
      "dtype": "float"
    }
  },
  "inputs": {
    "ibi": "#/sources/e4/streams/ibi",
    "bvp": "#/sources/e4/streams/bvp"
  },
  "streams": {
    "hr": {
      "name": "heart rate",
      "description": "heart rate calculated using IBI and BVP sensory data",
      "unit": "bpm",
      "frequency": 0,
      "index": "#/fields/t",
      "channels": [
        "#/fields/hr"
      ]
    }
  }
}

=== nirdslab/streaminghub/json/samples/master/analytic.sample.json
{
	"$schema": "../../analytic.schema.json",
	"info": {
		"version": "1.0.0",
		"timestamp": "2020-01-01T00:00:00Z",
		"checksum": "010203040506070809000A0B0C0D0E0F"
	},
	"sources": {
		"e4": "datasource.sample.json"
	},
	"inputs": {
		"ibi": "#/sources/e4/streams/ibi",
		"bvp": "#/sources/e4/streams/bvp"
	},
	"fields": {
		"t": "#/sources/e4/fields/t",
		"hr": {
			"name": "heart rate",
			"description": "heart rate in bpm",
			"dtype": "float"
		}
	},
	"streams": {
		"hr": {
			"name": "heart rate",
			"dtype": "float",
			"description": "heart rate calculated using IBI and BVP sensory data",
			"unit": "bpm",
			"frequency": 0,
			"index": "#/fields/t",
			"channels": [
				"#/fields/hr"
			]
		}
	}
}
