=== nirdslab/streaminghub/dfs/dataset.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "description": "schema of a dataset",
  "type": "object",
  "required": [
    "$schema",
    "info",
    "name",
    "description",
    "keywords",
    "authors",
    "sources",
    "fields",
    "groups",
    "resolver"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "info": {
      "$ref": "./dfs.schema.json#/definitions/info"
    },
    "name": {
      "description": "name of the dataset",
      "type": "string"
    },
    "description": {
      "description": "description of the dataset",
      "type": "string"
    },
    "keywords": {
      "description": "keywords that best describes the dataset",
      "type": "array",
      "minItems": 1,
      "items": {
        "description": "a keyword",
        "type": "string"
      }
    },
    "authors": {
      "description": "authors of the dataset",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "./dfs.schema.json#/definitions/author"
      }
    },
    "sources": {
      "description": "data sources for the dataset",
      "$ref": "./dfs.schema.json#/definitions/refs"
    },
    "fields": {
      "$ref": "./dfs.schema.json#/definitions/fields"
    },
    "groups": {
      "$ref": "./dfs.schema.json#/definitions/groups"
    },
    "resolver": {
      "description": "script to resolve data",
      "$ref": "./dfs.schema.json#/definitions/ref"
    }
  }
}

=== nirdslab/streaminghub/dfds/samples/master/dataset.sample.json
{
  "$schema": "../../dataset.schema.json",
  "info": {
    "version": "1.0.0",
    "timestamp": "2020-01-01T00:00:00Z",
    "checksum": "010203040506070809000A0B0C0D0E0F"
  },
  "name": "Heart Rate and GSR of Two Participants During a Running Task",
  "description": "This dataset contains recordings of heart rate of two participants during a running task. Recordings were obtained from an Empatica E4.",
  "keywords": [
    "heart-rate",
    "running"
  ],
  "authors": [
    {
      "name": "John Doe",
      "affiliation": "Example University",
      "email": "john@example.edu"
    },
    {
      "name": "Jane Doe",
      "affiliation": "Example University",
      "email": "jane@example.edu"
    }
  ],
  "sources": {
    "e4": "datasource.sample.json",
    "analytic": "analytic.sample.json"
  },
  "fields": {
    "gsr": "#/sources/e4/fields/gsr",
    "t": "#/sources/e4/fields/t",
    "hr": "#/sources/analytic/fields/hr"
  },
  "groups": {
    "subject": {
      "description": "ID of the subject",
      "attributes": [
        "001",
        "002"
      ]
    },
    "task": {
      "description": "ID of the running task",
      "attributes": [
        "T1",
        "T2",
        "T3"
      ]
    }
  },
  "resolver": "resolver.sample.py"
}

=== nirdslab/streaminghub/datasets/adhd_sin.json
{
  "$schema": "https://www.cs.odu.edu/~yasith/dfs/v2/dataset.schema.json",
  "info": {
    "version": "1.0.0",
    "timestamp": "2020-09-20T00:00:00",
    "checksum": "010203040506070809000A0B0C0D0E0F"
  },
  "name": "ADHD Audiovisual SIN Dataset",
  "description": "Gaze recordings of participants during an audiovisual SIN task",
  "keywords": [
    "SIN",
    "ADHD"
  ],
  "authors": [
    {
      "name": "Anne M. P. Michalek",
      "affiliation": "Old Dominion University",
      "email": "aperrott@odu.edu"
    }
  ],
  "sources": {
    "tobii": "../datasources/tobii_pro_x2_60.json"
  },
  "fields": {
    "RecordingTimestamp": "#/sources/tobii/fields/RecordingTimestamp",
    "GazePointLeftX (ADCSpx)": "#/sources/tobii/fields/GazePointLeftX (ADCSpx)",
    "GazePointLeftY (ADCSpx)": "#/sources/tobii/fields/GazePointLeftY (ADCSpx)",
    "PupilLeft": "#/sources/tobii/fields/PupilLeft",
    "GazePointRightX (ADCSpx)": "#/sources/tobii/fields/GazePointRightX (ADCSpx)",
    "GazePointRightY (ADCSpx)": "#/sources/tobii/fields/GazePointRightY (ADCSpx)",
    "PupilRight": "#/sources/tobii/fields/PupilRight"
  },
  "groups": {
    "subject": {
      "description": "The ID of each subject",
      "attributes": [
        "003",
        "012",
        "018",
        "024",
        "026",
        "030",
        "032",
        "034",
        "036",
        "038",
        "047"
      ]
    },
    "diagnosis": {
      "description": "The diagnosis of each subject",
      "attributes": [
        "ADHD",
        "NTYP"
      ]
    },
    "question": {
      "description": "The ID of in each question",
      "attributes": [
        "SET_A",
        "SET_B"
      ]
    },
    "noise": {
      "description": "The noise level of each question",
      "attributes": [
        "0",
        "5",
        "10",
        "15",
        "20",
        "25"
      ]
    }
  },
  "resolver": "adhd-sin.py"
}

=== nirdslab/streaminghub/metadata/datasets/dl_survey.json
{
  "$schema": "https://raw.githubusercontent.com/nirdslab/streaminghub/master/dfds/dataset.schema.json",
  "info": {
    "version": "1.0.0",
    "timestamp": "2020-09-20T00:00:00",
    "checksum": "010203040506070809000A0B0C0D0E0F"
  },
  "name": "dl_survey",
  "description": "Eye movements of participants during an audiovisual-SIN task",
  "keywords": [
    "SIN",
    "ADHD"
  ],
  "authors": [
    {
      "name": "Anne M. P. Michalek",
      "affiliation": "Old Dominion University",
      "email": "aperrott@odu.edu"
    }
  ],
  "sources": {
    "tobii": "../datasources/tobii_pro_x2_60.json"
  },
  "fields": {
    "t": "#/sources/tobii/fields/t",
    "x": "#/sources/tobii/fields/x",
    "y": "#/sources/tobii/fields/y",
    "d": "#/sources/tobii/fields/d"
  },
  "groups": {
    "subject": {
      "description": "The Group of Subjects",
      "attributes": [
        "multi1", "multi2", "multi3",
        "img1", "img2", "img3", "img4", "img5",
        "rtg1", "rtg2", "rtg3",
        "sng1", "sng2", "sng3", "sng4"
      ]
    },
    "diagnosis": {
      "description": "The diagnosis of each subject",
      "attributes": [
        "ADHD",
        "NTYP"
      ]
    },
    "question": {
      "description": "The ID of in each question",
      "attributes": [
        "SET_A",
        "SET_B"
      ]
    },
    "noise": {
      "description": "The noise level of each question",
      "attributes": [
        "0",
        "5",
        "10",
        "15",
        "20",
        "25"
      ]
    }
  },
  "resolver": "../resolvers/dl_survey.py"
}

=== nirdslab/streaminghub/metadata/datasets/adhd_sin.json
{
  "$schema": "https://raw.githubusercontent.com/nirdslab/streaminghub/master/dfs/dataset.schema.json",
  "info": {
    "version": "1.0.0",
    "timestamp": "2020-09-20T00:00:00",
    "checksum": "010203040506070809000A0B0C0D0E0F"
  },
  "name": "adhd_sin",
  "description": "Eye movements of participants during an audiovisual-SIN task",
  "keywords": [
    "SIN",
    "ADHD"
  ],
  "authors": [
    {
      "name": "Anne M. P. Michalek",
      "affiliation": "Old Dominion University",
      "email": "aperrott@odu.edu"
    }
  ],
  "sources": {
    "tobii": "../datasources/tobii_pro_x2_60.json"
  },
  "fields": {
    "t": "#/sources/tobii/fields/t",
    "x": "#/sources/tobii/fields/x",
    "y": "#/sources/tobii/fields/y",
    "d": "#/sources/tobii/fields/d"
  },
  "groups": {
    "subject": {
      "description": "The ID of each subject",
      "attributes": [
        "003",
        "012",
        "018",
        "024",
        "026",
        "030",
        "032",
        "034",
        "036",
        "038",
        "047"
      ]
    },
    "diagnosis": {
      "description": "The diagnosis of each subject",
      "attributes": [
        "ADHD",
        "NTYP"
      ]
    },
    "question": {
      "description": "The ID of in each question",
      "attributes": [
        "SET_A",
        "SET_B"
      ]
    },
    "noise": {
      "description": "The noise level of each question",
      "attributes": [
        "0",
        "5",
        "10",
        "15",
        "20",
        "25"
      ]
    }
  },
  "resolver": "../resolvers/adhd_sin.py"
}

=== nirdslab/streaminghub/metadata/datasets/pg_weather.json
{
  "$schema": "https://raw.githubusercontent.com/nirdslab/streaminghub/master/dfs/dataset.schema.json",
  "info": {
    "version": "1.0.0",
    "timestamp": "2020-09-20T00:00:00",
    "checksum": "010203040506070809000A0B0C0D0E0F"
  },
  "name": "Weather Dataset",
  "description": "Weather Dataset",
  "keywords": [
    "Weather",
    "Climate"
  ],
  "authors": [
    {
      "name": "Gabriel Dzodom",
      "affiliation": "Texas A&M University",
      "email": "gabriel.dzodom@tamu.edu"
    },
    {
      "name": "Frank Shipman",
      "affiliation": "Texas A&M University",
      "email": "shipman@cse.tamu.edu"
    }
  ],
  "sources": {
    "weather": "../datasources/weather.json"
  },
  "fields": {
    "maxtemperature": "#/sources/weather/fields/maxtemperature",
    "meantemperature": "#/sources/weather/fields/meantemperature",
    "mintemperature": "#/sources/weather/fields/mintemperature",
    "maxdewpoint": "#/sources/weather/fields/maxdewpoint",
    "meandewpoint": "#/sources/weather/fields/meandewpoint",
    "mindewpoint": "#/sources/weather/fields/mindewpoint",
    "maxhumidity": "#/sources/weather/fields/maxhumidity",
    "meanhumidity": "#/sources/weather/fields/meanhumidity",
    "minhumidity": "#/sources/weather/fields/minhumidity",
    "maxsealevelpressure": "#/sources/weather/fields/maxsealevelpressure",
    "meansealevelpressure": "#/sources/weather/fields/meansealevelpressure",
    "minsealevelpressure": "#/sources/weather/fields/minsealevelpressure",
    "maxvisibility": "#/sources/weather/fields/maxvisibility",
    "meanvisibility": "#/sources/weather/fields/meanvisibility",
    "minvisibility": "#/sources/weather/fields/minvisibility",
    "maxwindspeed": "#/sources/weather/fields/maxwindspeed",
    "meanwindspeed": "#/sources/weather/fields/meanwindspeed",
    "maxgustspeed": "#/sources/weather/fields/maxgustspeed",
    "precipitation": "#/sources/weather/fields/precipitation",
    "cloudcover": "#/sources/weather/fields/cloudcover",
    "winddirection": "#/sources/weather/fields/winddirection",
    "date": "#/sources/weather/fields/date"
  },
  "groups": {
    "city": {
      "description": "The city of the corresponding weather data",
      "attributes": [
        "albuquerque",
        "atlanta",
        "billings",
        "boise",
        "boston",
        "buffalo",
        "charlotte",
        "chicago",
        "cleveland",
        "columbus",
        "dallas",
        "denver",
        "des moines",
        "detroit",
        "district of columbia",
        "el paso",
        "fargo",
        "indianapolis",
        "jackson",
        "jacksonville",
        "kansas city",
        "las vegas",
        "lincoln",
        "little rock",
        "los angeles",
        "louisville",
        "manhattan",
        "memphis",
        "miami",
        "milwaukee",
        "minneapolis",
        "missoula",
        "montgomery",
        "nashville",
        "new orleans",
        "oklahoma city",
        "philadelphia",
        "phoenix",
        "pittsburgh",
        "portland",
        "rapid city",
        "saint louis",
        "salt lake city",
        "san antonio",
        "san francisco",
        "seattle",
        "sioux falls",
        "spokane",
        "tucson"
      ]
    },
    "state": {
      "description": "The city of the corresponding weather data",
      "attributes": [
        "alabama",
        "arizona",
        "arkansas",
        "california",
        "colorado",
        "florida",
        "georgia",
        "illinois",
        "indiana",
        "iowa",
        "kentucky",
        "louisiana",
        "maine",
        "massachusetts",
        "michigan",
        "minnesota",
        "mississippi",
        "missouri",
        "montana",
        "nebraska",
        "nevada",
        "new mexico",
        "new york",
        "north carolina",
        "north dakota",
        "ohio",
        "oklahoma",
        "oregon",
        "pennsylvania",
        "south dakota",
        "tennessee",
        "texas",
        "utah",
        "washington",
        "washington dc",
        "wisconsin"
      ]
    }
  },
  "resolver": "../resolvers/pg_weather.py"
}

=== nirdslab/streaminghub/datasets/n_back.json
{
  "$schema": "https://raw.githubusercontent.com/nirdslab/streaminghub/master/dfs/dataset.schema.json",
  "info": {
    "version": "1.0.0",
    "timestamp": "2020-09-20T00:00:00",
    "checksum": "010203040506070809000A0B0C0D0E0F"
  },
  "name": "N-Back Dataset",
  "description": "Eye movements of participants during a n-back task",
  "keywords": ["n-back"],
  "authors": [
    { "name": "Andrew T. Duchowski", "affiliation": "Clemson University", "email": "duchowski@clemson.edu" }
  ],
  "sources": {
    "eyelink": "../datasources/sr_research_eyelink_1000.json"
  },
  "fields": {
    "t": "#/sources/eyelink/fields/t",
    "x": "#/sources/eyelink/fields/x",
    "y": "#/sources/eyelink/fields/y",
    "d": "#/sources/eyelink/fields/d"
  },
  "groups": {
    "subject": {
      "description": "The ID of each subject",
      "attributes": [
        "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10",
        "S11", "S12", "S13", "S14", "S15", "S16", "S17", "S18", "S19"
      ]
    },
    "mode": {
      "description": "The mode of experiment",
      "attributes": [ "baseline", "task" ]
    },
    "task": {
      "description": "The ID of the task",
      "attributes": [ "1back", "2back" ]
    },
    "position": {
      "description": "The position of each task",
      "attributes": [ "top_left", "top_right", "center", "bottom_left", "bottom_right"]
    }
  },
  "resolver": "n_back.py"
}
