=== nirdslab/streaminghub/json/datasource.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"description": "schema of a meta-stream",
	"type": "object",
	"required": [
		"$schema",
		"info",
		"device",
		"fields",
		"streams"
	],
	"additionalProperties": false,
	"properties": {
		"$schema": {
			"type": "string"
		},
		"info": {
			"$ref": "dfs.schema.json#/definitions/info"
		},
		"device": {
			"$ref": "dfs.schema.json#/definitions/device"
		},
		"fields": {
			"$ref": "dfs.schema.json#/definitions/fields"
		},
		"streams": {
			"$ref": "dfs.schema.json#/definitions/streams"
		}
	}
}

=== nirdslab/streaminghub/json/samples/01-meta-stream.json
{
  "$schema": "../meta-stream.jsd",
  "info": {
    "version": "1.0.0",
    "checksum": "010203040506070809000A0B0C0D0E0F"
  },
  "device": {
    "model": "E4",
    "manufacturer": "Empatica",
    "category": "Wristband"
  },
  "fields": [
    {
      "id": "acc_x",
      "name": "x - acceleration",
      "description": "Acceleration in the X axis",
      "dtype": "float"
    },
    {
      "id": "acc_y",
      "name": "y - acceleration",
      "description": "Acceleration in the Y axis",
      "dtype": "float"
    },
    {
      "id": "acc_z",
      "name": "z - acceleration",
      "description": "Acceleration in the Z axis",
      "dtype": "float"
    },
    {
      "id": "bvp",
      "name": "blood volume pulse",
      "description": "Blood Volume Pulse",
      "dtype": "float"
    },
    {
      "id": "gsr",
      "name": "galvanic skin response",
      "description": "Galvanic Skin Response",
      "dtype": "float"
    },
    {
      "id": "ibi",
      "name": "inter beat interval",
      "description": "The interval between two consecutive heartbeats",
      "dtype": "float"
    },
    {
      "id": "tmp",
      "name": "skin temperature",
      "description": "Skin Temperature on the Wrist",
      "dtype": "float"
    },
    {
      "id": "bat",
      "name": "battery level",
      "description": "Battery Level of the Device",
      "dtype": "float"
    },
    {
      "id": "tag",
      "name": "tag",
      "description": "Press of the Tag Button",
      "dtype": "float"
    }
  ],
  "streams": [
    {
      "name": "acceleration",
      "description": "3-axis acceleration (unit - gravity)",
      "unit": "g",
      "frequency": 32,
      "channels": [
        "acc_x",
        "acc_y",
        "acc_z"
      ]
    },
    {
      "name": "blood volume pulse",
      "description": "Blood Volume Pulse (unit - lumen)",
      "unit": "lm",
      "frequency": 64,
      "channels": [
        "bvp"
      ]
    },
    {
      "name": "galvanic skin response",
      "description": "Galvanic Skin Response (unit - micro siemens)",
      "unit": "S",
      "frequency": 0,
      "channels": [
        "gsr"
      ]
    },
    {
      "name": "inter-beat interval",
      "description": "Inter-Beat Interval (unit - seconds)",
      "unit": "s",
      "frequency": 0,
      "channels": [
        "ibi"
      ]
    },
    {
      "name": "skin temperature",
      "description": "Skin Temperature (unit - celsius)",
      "unit": "c",
      "frequency": 0,
      "channels": [
        "tmp"
      ]
    },
    {
      "name": "battery level",
      "description": "Device Battery (unit - percent)",
      "unit": "%",
      "frequency": 0,
      "channels": [
        "bat"
      ]
    },
    {
      "name": "tag",
      "description": "Tag recorded upon button press",
      "unit": "",
      "frequency": 0,
      "channels": [
        "tag"
      ]
    }
  ]
}
